-   hosts:  localhost
    connection: local
    become: true

    pre_tasks:
      -  name: update repositories
         apt:
            update_cache: yes
         changed_when: False

    tasks:
       - name: Include tasks
          ansible.builtin.include_tasks:
            file: tasks/packages.yml
